/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ControlePlaylist;
import model.Usuario;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.DefaultListModel;
/**
 *
 * @author Rafael
 */
      
public class Playlist extends javax.swing.JFrame {
    
    /**
     * Creates new form videos
     */
    
    
    public Playlist(Usuario usuario) {
        initComponents();
        c = new ControlePlaylist(this, usuario);
    }
    
    public JList<String> getListaPlaylists() {
        return ListaPlaylists;
    }
    
    public JList<String> getListaVideoPlaylist() {
        return ListaVideoPlaylist;
    }
    
    public JTextField getBuscaPlaylists() {
        return BuscaPlaylists;
    }
    
    public int getPlaylistSelecionada() {
        int indice = ListaPlaylists.getSelectedIndex();
        if (indice == -1) return -1;
        String texto = ListaPlaylists.getSelectedValue();
        return Integer.parseInt(texto.split(" - ")[0]);
    }
    public void limparVideos() {
    ListaVideoPlaylist.setModel(new DefaultListModel<>());
}
    public int getVideoSelecionado() {
    int indice = ListaVideoPlaylist.getSelectedIndex();
    if (indice == -1) return -1;
    String texto = ListaVideoPlaylist.getSelectedValue();
    return Integer.parseInt(texto.split(" - ")[0]);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BTExcluir = new javax.swing.JButton();
        BTCriar = new javax.swing.JButton();
        botaopesquisar = new javax.swing.JButton();
        BuscaPlaylists = new javax.swing.JTextField();
        BTEditar = new javax.swing.JButton();
        BTFavorito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPlaylists = new javax.swing.JList<>();
        TXTplaylist2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaVideoPlaylist = new javax.swing.JList<>();
        TXTvidelosPlaylists = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTExcluir.setText("Excluir");
        BTExcluir.addActionListener(this::BTExcluirActionPerformed);

        BTCriar.setText("Criar");
        BTCriar.addActionListener(this::BTCriarActionPerformed);

        botaopesquisar.setText("Pesquisar");

        BuscaPlaylists.addActionListener(this::BuscaPlaylistsActionPerformed);

        BTEditar.setText("Editar");
        BTEditar.addActionListener(this::BTEditarActionPerformed);

        BTFavorito.setText("Favoritos");
        BTFavorito.addActionListener(this::BTFavoritoActionPerformed);

        ListaPlaylists.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaPlaylists);

        TXTplaylist2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TXTplaylist2.setText("PlayLists");
        TXTplaylist2.addActionListener(this::TXTplaylist2ActionPerformed);

        ListaVideoPlaylist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaVideoPlaylist);

        TXTvidelosPlaylists.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TXTvidelosPlaylists.setText("Videos da PlayList");
        TXTvidelosPlaylists.addActionListener(this::TXTvidelosPlaylistsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(BTFavorito)
                        .addGap(18, 18, 18)
                        .addComponent(BTCriar)
                        .addGap(33, 33, 33)
                        .addComponent(BTEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(TXTplaylist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TXTvidelosPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaopesquisar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BuscaPlaylists, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXTplaylist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaopesquisar)
                    .addComponent(BuscaPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TXTvidelosPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTExcluir)
                    .addComponent(BTEditar)
                    .addComponent(BTCriar)
                    .addComponent(BTFavorito))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void BuscaPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {                                               
        c.buscar();
    }                                              

    private void BTEditarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        c.editar();
    }                                        

    private void TXTplaylist2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void TXTvidelosPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void BTFavoritoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        c.adicionarFavorito();
    }                                          

    private void BTCriarActionPerformed(java.awt.event.ActionEvent evt) {                                        
       c.criar();
    }                                       

    private void BTExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        c.excluir();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        /* Create and display the form */
    }
    private ControlePlaylist c;
    // Variables declaration - do not modify                     
    private javax.swing.JButton BTCriar;
    private javax.swing.JButton BTEditar;
    private javax.swing.JButton BTExcluir;
    private javax.swing.JButton BTFavorito;
    private javax.swing.JTextField BuscaPlaylists;
    private javax.swing.JList<String> ListaPlaylists;
    private javax.swing.JList<String> ListaVideoPlaylist;
    private javax.swing.JTextField TXTplaylist2;
    private javax.swing.JTextField TXTvidelosPlaylists;
    private javax.swing.JButton botaopesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration                   
}
